--[[
    IPTV Channel Handler for OpenResty
    Loads channels from local JSON file (pre-generated by Python script)
]]

local cjson = require("cjson.safe")

local _M = {}

-- Channel storage
local channels = {}
local last_load = 0

-- Path to channels JSON
local CHANNELS_FILE = "/etc/openresty/data/channels.json"

-- Load channels from JSON file
function _M.load_from_file()
    ngx.log(ngx.INFO, "Loading channels from: " .. CHANNELS_FILE)
    
    local file = io.open(CHANNELS_FILE, "r")
    if not file then
        ngx.log(ngx.ERR, "Could not open channels file: " .. CHANNELS_FILE)
        return false
    end
    
    local content = file:read("*all")
    file:close()
    
    local data, err = cjson.decode(content)
    if not data then
        ngx.log(ngx.ERR, "Failed to parse channels JSON: " .. (err or "unknown"))
        return false
    end
    
    channels = data
    last_load = ngx.time()
    
    local count = 0
    local multi = 0
    for _, ch in pairs(channels) do
        count = count + 1
        if ch.server_count and ch.server_count > 1 then
            multi = multi + 1
        end
    end
    
    ngx.log(ngx.INFO, "Loaded " .. count .. " channels (" .. multi .. " with backup servers)")
    return true
end

-- Initialize on first load
function _M.init()
    if next(channels) == nil then
        _M.load_from_file()
    end
end

-- Refresh (reload from file)
function _M.refresh()
    return _M.load_from_file()
end

-- Get all channels (for API)
function _M.get_all()
    _M.init()
    
    -- Return simplified list (without server URLs - hide them!)
    local result = {}
    for ch_id, ch in pairs(channels) do
        result[ch_id] = {
            name = ch.name,
            group = ch.group,
            logo = ch.logo,
            server_count = ch.server_count or (ch.servers and #ch.servers or 1)
        }
    end
    return result
end

-- Get stream URL for a channel
function _M.get_stream_url(channel_id, server_idx)
    _M.init()
    
    if not channels[channel_id] then
        return nil
    end
    
    local ch = channels[channel_id]
    local servers = ch.servers
    
    if not servers or #servers == 0 then
        return nil
    end
    
    local idx = (server_idx or 0) + 1  -- Lua is 1-indexed
    
    if idx > #servers then
        idx = 1
    end
    
    return servers[idx]
end

-- Get channel info
function _M.get_channel(channel_id)
    _M.init()
    return channels[channel_id]
end

-- Main handler for /api/channels endpoint
if ngx and ngx.var then
    local result = _M.get_all()
    ngx.say(cjson.encode(result))
end

return _M
